const stylesMovieList2 = {
  movieList: {
    display: 'flex',
    'flex-flow': 'row wrap',
    'justify-content': 'space-between',
    'align-items': 'stretch',
    width: '100%',
    'max-width': 1200,
    margin: [0, 'auto'],
    '& a': {
      padding: 5,
      margin: [15, 'auto'],
      border: '1px solid #eee',
      'text-decoration': 'none',
      color: '#242d32',
      '&:hover': {
        'box-shadow': '1px 3px 4px 2px rgba(0,0,0,0.5)',
      },
    },
    '& h1': {
      width: '100%',
      'font-size': 30,
      'text-align': 'center',
    },
  },
  MovieCard: {
    display: 'flex',
    'flex-flow': 'row wrap',
    'justify-content': 'flex-start',
    'align-items': 'stretch',
    width: '100%',
    'max-width': 350,
    padding: 0,
    '& img': {
      display: 'block',
      width: '100%',
    },
    '& h3': {
      display: 'block',
      margin: '20px 0',
      padding: [0, 10],
      width: '100%',
      'text-decoration': 'none',
      'text-align': 'center',
    },
    '& span': {
      display: 'block',
      width: '100%',
      margin: '10px 0',
      padding: [0, 10],
      'text-align': 'right',
      'text-decoration': 'none',
      color: '#164ebe',
    },
    '& p': {
      width: '100%',
      margin: [0, 0, 20],
      padding: [0, 10],
      'text-align': 'justify',
      'text-decoration': 'none',
    },
  },
  pagination: {
    display: 'flex',
    'flex-flow': 'row wrap',
    'justify-content': 'flex-start',
    'align-items': 'stretch',
    width: '100%',
  },
  page: {
    padding: 10,
    'border-top': '1px solid #ff0000',
    'border-bottom': '1px solid #ff0000',
    'border-left': '1px solid #ff0000',
    'background-color': '#ff0000',
    color: '#fff',
    cursor: 'pointer',
    transition: 'background-color .3s ease, color .3s ease',
    '&:last-child': {
      'border-right': '1px solid #ff0000',
    },
    '& active': {
      'border-top': '1px solid #ff0000,',
      'border-bottom': '1px solid #ff0000',
      'border-left': '1px solid #ff0000',
      'background-color': '#fff',
      color: '#ff0000',
    },
    '&:hover': {
      'background-color': '#fff',
      color: '#ff0000',
      transition: 'background-color .3s ease, color .3s ease',
    },
    '&:focus': {
      'background-color': '#fff',
      color: '#ff0000',
      transition: 'background-color .3s ease, color .3s ease',
    },
  },
};

export default stylesMovieList2;
